name: acter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  meta: ^1.11.0
  gsheets: ^0.5.0
  loader_overlay: ^4.0.0
  flutter_dotenv: ^5.1.0
  async: ^2.11.0
  provider: ^6.1.2
  googleapis: ^11.4.0
  http: ^1.2.1
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  path_provider: ^2.1.3
  googleapis_auth: ^1.6.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
